# logging
logging:
  level:
    root: DEBUG

# spring
spring:
  main:
    web-application-type: none
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
  batch:
    job:
      enabled: false
      names: ~
    jdbc:
      initialize-schema: embedded
    datasource:
      hikari:
        minimum-idle: 1
        maximum-pool-size: 3

# batch
batch:
  data-home: ${user.home}/.arch4j
