# logging
logging:
  level:
    root: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

# spring
spring:
  output:
    ansi:
      enabled: DETECT
  datasource:
    driver-class-Name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:apps;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  data:
    jpa:
      show-sql: true
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          use_sql_comments: true
          globally_quoted_identifiers: true