# logging
logging:
  level:
    root: INFO

# spring
spring:
  thymeleaf:
    cache: false
  datasource:
    hikari:
      driver-class-Name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://192.168.0.2:3306/arch4j
      username: arch4j
      password: arch4j
      minimum-idle: 10
      maximum-pool-size: 20
  mail:
    host: smtp.mailtrap.io
    port: 25
    username: 987a77fac40349
    password: cfad266492f5fa
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enaled: true

# core
core:
  storage:
    storage-client:
      properties:
        location: /nfs

