# logging
logging:
  level:
    root: DEBUG

# server
server:
  port: 8080
  error:
    include-message: always
  tomcat:
    mbeanregistry:
      enabled: true

# management
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown,threaddump,heapdump

# spring
spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    enabled: true
    cache: false
  jackson:
    serialization:
      indent_output: true
  data:
    web:
      pageable:
        prefix: _
        default-page-size: 100
        max-page-size: 1000
  security:
    user:
      name: test
      password: test
      roles: TEST


