# logging
logging:
  level:
    root: DEBUG
    org.apache.catalina.core.AprLifecycleListener: INFO
    org.apache.tomcat.util.compat: INFO
    org.apache.coyote.http11: INFO

# server
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  tomcat:
    use-relative-redirects: true
    mbeanregistry:
      enabled: true
  forward-headers-strategy: framework

# management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown,threaddump,heapdump
  info:
    os.enabled: true
    java.enabled: true
    build.enabled: true
    defaults.enabled: true
    git.enabled: true

# spring
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: embedded
  data:
    web:
      pageable:
        prefix: _
        default-page-size: 100
        max-page-size: 1000
  jackson:
    serialization:
      indent_output: true
  thymeleaf:
    enabled: true
    cache: false
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/static/
        - classpath:/templates/

# springdoc
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    enabled: true
    operations-sorter: alpha
  group-configs:
    - group: version 1.0
      paths-to-match: /api/v1/**

