# logging
logging:
  level:
    root: DEBUG
    org.apache.catalina.core.AprLifecycleListener: INFO
    org.apache.tomcat.util.compat: INFO
    org.apache.coyote.http11: INFO

# server
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
  error:
    include-message: always
    include-binding-errors: always
  tomcat:
    use-relative-redirects: true
    mbeanregistry:
      enabled: true
  forward-headers-strategy: framework

# management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown,threaddump,heapdump
  info:
    os.enabled: true
    java.enabled: true
    build.enabled: true
    defaults.enabled: true
    git.enabled: true

# spring
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: embedded
  data:
    web:
      pageable:
        prefix: _
        default-page-size: 100
        max-page-size: 10000
      sort:
        sort-parameter: _sort
  jackson:
    serialization:
      indent_output: true
  thymeleaf:
    enabled: true
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      resolve-lazily: true
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/static/
        - classpath:/templates/
  sleuth:
    enabled: false
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://127.0.0.1:9411
    service:
      name: ~

# springdoc
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    disable-swagger-default-url: true
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: version 1.0
      paths-to-match: /api/v1/**

# web
web:
  theme: _default
  brand: <img class="icon" src="/static/image/arch4j-icon.svg"/><img src="/static/image/arch4j-title.svg"/>
  favicon: /static/image/arch4j-icon.svg
  title: ARCH4J (Application Archetype for Java)
  index: git/arch4j/README.md
  security-policy: AUTHENTICATED
  security-signing-key: ahD3N&nctCE&aDenBKHu)tav7FyqMw6vPHXRtw7)WbWIvX8Xdtrs4fu*E9UXN58L
  security-expire-minutes: 60
