# logging
logging:
  level:
    root: DEBUG
    org.apache.catalina.core.AprLifecycleListener: INFO
    org.apache.tomcat.util.compat: INFO
    org.apache.coyote.http11: INFO

# server
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  tomcat:
    mbeanregistry:
      enabled: true

# management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown,threaddump,heapdump

# spring
spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    enabled: true
    cache: false
  jackson:
    serialization:
      indent_output: true
  data:
    web:
      pageable:
        prefix: _
        default-page-size: 100
        max-page-size: 1000
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: embedded
  security:
    anonymous:
      authorities: ~

# springdoc
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    path: /api
    operations-sorter: alpha
  group-configs:
    - group: version 1.0
      paths-to-match: /api/v1/**





