# logging
logging:
  level:
    root: DEBUG
    com.zaxxer.hikari: ERROR
    com.zaxxer.hikari.HikariConfig: DEBUG

# spring
spring:
  shell:
    logging:
        level: ERROR
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    script:
      enabled: false
    jline:
      terminal: jline.UnsupportedTerminal


