name: Auto Release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    env:
      RELEASE_VERSION: 1.0.0-SNAPSHOT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and Test
        run: |
          ./gradlew clean bootDistZip -x test

      - name: Upload Additional Files
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            ${{ github.workspace }}/arch4j-web/build/distributions/arch4j-web-boot-${{ env.RELEASE_VERSION }}.zip
            ${{ github.workspace }}/arch4j-cli/build/distribution/arch4j-cli-boot-${{ env.RELEASE_VERSION }}.zip
            ${{ github.workspace }}/arch4j-batch/build/distribution/arch4j-batch-boot-${{ env.RELEASE_VERSION }}.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.RELEASE_VERSION }}-${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Web
        id: upload-release-asset-web
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/arch4j-web/build/distributions/arch4j-web-boot-${{ env.RELEASE_VERSION }}.zip
          asset_name: arch4j-web-boot-${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset Cli
        id: upload-release-asset-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/arch4j-cli/build/distributions/arch4j-cli-boot-${{ env.RELEASE_VERSION }}.zip
          asset_name: arch4j-cli-boot-${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset Batch
        id: upload-release-asset-batch
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/arch4j-batch/build/distributions/arch4j-batch-boot-${{ env.RELEASE_VERSION }}.zip
          asset_name: arch4j-batch-boot-${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
